# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lab 2' do
  # Pods for Lab 2
  platform :ios, '8.0'
  # Uncomment the next line when you want all Pods as static framework
  # use_modular_headers!
  pod 'SDWebImage', :modular_headers => true
end
