# Generated by Django 3.1.5 on 2021-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210107_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(blank=True),
        ),
    ]
